import json, csv

# Paste từng mảng JSON vào đây
raw_data = {
    "Ăn uống": [
      "ăn sáng", "an sang", "tien an sang", "ăn trưa", "an trua", "com trua", "cơm trưa", "tien com trua", "ăn tối", "an toi", "tien an toi", "ăn đêm", "an dem", "an khuya", "an chieu", "pho", "phở", "pho thin", "tien pho", "bun bo", "bún bò", "bun bo hue", "com tam", "cơm tấm", "com tam ba ghien", "hu tiu", "hủ tiếu", "banh mi", "bánh mì", "bm", "xoi", "xôi", "chao", "cháo", "mi quang", "bun cha", "bún chả", "bun dau", "bún đậu", "bun dau mam tom", "lau", "lẩu", "lau thai", "tien lau", "nuong", "nướng", "an nuong", "buffet", "an buffet", "bun rieu", "bun thit nuong", "banh canh", "bánh cuốn", "banh uot", "dimsum", "an oc", "ốc", "tien oc", "hai san", "hải sản", "bít tết", "beefsteak", "ga ran", "gà rán", "kfc", "lotteria", "texas", "mcdonalds", "jollibee", "popeyes", "pizza", "4ps", "pizza 4p", "domino", "the pizza company", "haidilao", "hdl", "manwah", "kichi", "kichi kichi", "gogi", "gogi house", "kpub", "san fu lou", "ba gác", "warning zone", "tra sua", "trà sữa", "ts", "tien ts", "ts koi", "koi the", "phê la", "phela", "the alley", "gongcha", "mixue", "highland", "highlands", "cf highlands", "phuc long", "phúc long", "tch", "the coffee house", "katinat", "starbucks", "sbux", "cf", "cafe", "cà phê", "tien cf", "aha", "citi ground", "cheese coffee", "nuoc ep", "sinh to", "rau ma", "rau má mix", "an vat", "ăn vặt", "ca vien chien", "cá viên", "banh trang tron", "shopeefood", "spf", "order shopeefood", "grabfood", "befood", "gofood", "baemin", "order baemin", "tien ship do an", "order do an", "dat com", "dat do an", "tien com", "tiền cơm", "com thang", "cơm tháng", "an voi cty", "an trua cty", "com van phong", "share tien an", "tra tien an", "tra tien com", "an khao", "tien an khao", "an sinh nhat", "an sn", "lien hoan", "liên hoan", "tien lien hoan", "an nha hang", "an chay", "cơm chay", "an hqua", "an toi qua", "tien an hqua", "an voi e", "an voi ban", "dinner", "lunch", "breakfast", "an kem", "kem", "sua chua tran chau", "che", "chè", "tien che", "banh ngot", "bánh kem", "mua banh sn", "banh sinh nhat", "an chung", "ck tien an", "thue an", "tien an uong", "qũy ăn uống", "com rang", "mi xao", "mỳ cay", "mi cay sasin", "sushi", "sashimi", "đồ hàn", "đồ nhật", "tokbokki", "dokki", "dookki", "bbh", "bun bo 2 to", "dinner w gf", "cf q1", "an lẫu", "cf zí ghệ", "ts trân châu", "ăn xịn", "ăn sang", "côm chóa", "đi măm", "com tho", "ăn sáng 🍳", "cf ☕", "ts 🧋", "gà rán 🍗", "an sag", "cơm tứm", "trà xữa", "phở zới a", "nhậu", "tien nhau", "di nhau", "an lau t7", "com nieu", "beamin toi", "shopeefood trưa", "an cúng", "nhau oc", "ăn khuya nha", "cf hqua m nhe", "ăn lẩu hqua", "ck com t5", "com hop"
    ],       # paste array từ LLM
    "Di chuyển": [
      "grab", "grab bike", "grabcar", "be", "bebike", "xanh sm", "xsm", "taxi", "gojek", "tien xe", "tiền xe", "ve xe", "vé xe", "do xang", "đổ xăng", "gui xe", "gửi xe", "tien taxi", "tiền taxi", "xe om", "xe ôm", "ve may bay", "vé máy bay", "ve tau", "vé tàu", "phi ship", "phí ship", "tien ship", "tiền ship", "ship", "lalamove", "ahamove", "phi bot", "phí bot", "vetc", "epass", "phi cao toc", "phí cao tốc", "tien do xang", "xang", "xăng", "phi gui xe", "tien gui xe", "gui xe thang", "gửi xe tháng", "book xe", "book grab", "xe di tinh", "xe đi tỉnh", "ve xe khach", "vé xe khách", "vx", "vx ve que", "vé xe về quê", "xe khach", "xe khách", "tra tien grab", "trả tiền grab", "tien xe ve", "tiền xe về", "phi duong bo", "phí đường bộ", "ve mb", "vé mb", "vietjet", "bamboo", "vna", "tien di chuyen", "tiền di chuyển", "di lai", "đi lại", "giao hang", "giao hàng", "tien xe bus", "tiền xe bus", "ve bus", "vé bus", "the bus", "thẻ bus", "mrt", "ve tau dien", "vé tàu điện", "tien tau", "tiền tàu", "thue xe", "thuê xe", "tien thue xe", "tiền thuê xe", "coc xe", "cọc xe", "sua xe", "sửa xe", "tien sua xe", "thay nhot", "thay nhớt", "bao duong xe", "bảo dưỡng xe", "rua xe", "rửa xe", "tien rua xe", "mai linh", "vinasun", "taxi san bay", "di san bay", "đi sân bay", "grab q1", "grab q7", "be nha", "be cty", "grab di lam", "grab đi làm", "xe ghep", "xe ghép", "tien xe ghep", "bao xe", "bao chuyến", "thue oto", "tien grab gium", "ck grab", "xe ve sg", "xe đi hn", "vé mbay", "vmbay", "taxi t7", "grab sang", "bebike toi", "xanhsm 🚕", "do xang 50k", "xang 50", "xang xe", "đổ xang", "tien do xang 🚗", "xe di tq", "vx sg đl", "vx dalat", "ve xe p.trang", "phuong trang", "thanh buoi", "ve xe tbh", "gui xe aeon", "gxe", "gx", "tien gui bãi", "gui xe oto", "phi gui oto", "ve may bay qte", "vé mb tet", "vmb tết", "xe tết", "ve xe tet", "vx tet", "tien ship hang", "ship do", "tien ship shopee", "ship sp", "ship lala", "ship cod", "tien aha", "book aha", "phi bot ql1", "tien tram thu phi", "nap vetc", "nap epas", "ck epass", "phi cao toc ltd", "cao toc", "bot", "tien cau duong", "taxi hqua", "taxi noibai", "taxi tsn", "grab ra sb", "tien grab 🛵", "book be 🚗", "ck tien xe", "tien thue xe may", "thue xe may đà lạt", "coc oto", "ck coc xe", "rua oto", "rua xe may", "thay xam xe", "thay lốp", "va xe", "vá xe", "tien va xe", "cuu ho xe", "cứu hộ oto", "keo xe", "tiền kéo xe", "phi dang kiem xe", "dk xe", "tien xe 50k", "share tien grab", "share xe", "grap", "grapbike", "tien grap", "đặt xe", "ck dat xe", "dat gium xe", "taxi grap", "shiper", "tien cho shiper", "ck shiper", "tiền ship 📦", "xăng ⛽", "đổ xăng 🛵", "ve mbay ✈️", "ve tau 🚆", "vx khach", "ck vx", "tien xe dap", "thue xe dap", "xe dap cong cong", "tien thue xe dap"
    ],
    "Mua sắm": [
      "shopee", "lazada", "tiktok", "tiktok shop", "mua do", "mua đồ", "quan ao", "quần áo", "tien giay", "tiền giày", "mua tui", "mua túi", "my pham", "mỹ phẩm", "son", "skincare", "ao thun", "áo thun", "quan jean", "quần jean", "bhx", "bach hoa xanh", "bách hóa xanh", "coopmart", "coop", "winmart", "sieu thi", "siêu thị", "mua do sieu thi", "taobao", "tao bao", "tq", "mua do tq", "order taobao", "order", "dat hang", "đặt hàng", "chot don", "chốt đơn", "thanh toan shopee", "shopeepay", "spay", "mua sach", "mua sách", "mua dien thoai", "mua đt", "mua dt", "tra gop dt", "mua laptop", "tien lap", "mua dong ho", "mua đồng hồ", "phu kien", "phụ kiện", "op lung", "ốp lưng", "sac dt", "sạc đt", "mua hoa", "tien hoa", "quà", "qua sinh nhat", "quà sn", "mua qua", "mua quà", "trang suc", "trang sức", "pji", "pnj", "doji", "mua vang", "mua vàng", "tien vang", "mua quan ao tet", "đồ tết", "mua do tet", "tap hoa", "tạp hóa", "mua tap hoa", "mua banh keo", "bánh kẹo", "trai cay", "trái cây", "mua hoa qua", "mua trai cay", "thit", "thịt", "mua thit", "hai san", "hải sản", "mua ca", "mua rau", "di cho", "đi chợ", "tien di cho", "tiền đi chợ", "tien cho", "ck shopee", "ck lazada", "ck mua do", "thanh toan don hang", "don hang", "don shopee", "mĩ phẩm", "skincare t5", "mua kem chong nang", "kcn", "mua kcn", "mua ao khoac", "áo khoác", "giay the thao", "giày sneaker", "mua sneaker", "tien mua do", "mua bim", "bỉm sữa", "mua sua", "sữa em bé", "mua do be", "đồ sơ sinh", "do choi", "đồ chơi", "mua do choi", "lego", "mua lego", "mua ban phím", "ban phim", "chuot may tinh", "chuột pc", "man hinh", "màn hình", "mua linh kien", "linh kien pc", "đồ điện tử", "dien may xanh", "đmx", "dien may", "mua tu lanh", "mua tivi", "mua may giat", "mua quat", "quạt máy", "mua noi chien", "nồi chiên k dâu", "mua do bep", "đồ bếp", "chen dia", "chén dĩa", "mua giuong", "mua nem", "nệm", "chăn ga", "chan ga", "mua sofa", "mua ghe", "mua ban", "bàn ghế", "noi that", "nội thất", "ikea", "mua do decor", "decor", "do trang tri", "mua cay", "mua cây", "chau cay", "chậu cây", "mua thu cung", "thức ăn chó", "do an meo", "hạt cho mèo", "cát mèo", "mua cat meo", "shop meo", "pet shop", "quanao 👗", "mua do 👠", "sieu thi 🛒", "shopee 🛍️", "chot don 📦", "laz 📦", "shope", "shoping", "mua săm", "mua giay dép", "mua guoc", "mua vay", "mua váy", "vay thiet ke", "váy tk", "ck mua ao", "ao somi", "áo sơmi", "quan tay", "mua do hqua", "thanh toan shop", "ck shop", "tien mua do t7", "shop online", "mua live", "mua livestream", "chot live"
    ],
    "Giải trí": [
      "xem phim", "cgv", "galaxy", "bhd", "lotte", "netflix", "netflix t5", "spotify", "yt premium", "vieon", "fpt play", "bida", "bia", "tien bida", "bida lỗ", "net", "cyber", "tien net", "the game", "nap the game", "steam", "nintendo", "garena", "zing", "vng", "nhau", "tien nhau", "pub", "bar", "cf", "cafe", "cf ban", "cf sang", "cf highlands", "phúc long", "starbucks", "karaoke", "kara", "hat kara", "di chill", "boardgame", "tiền xem phim", "ve xem phim", "vé phim", "xem phim 🎬", "cgv 🍿", "tien rap", "rap cgv", "ve cgv", "bap nuoc cgv", "netflix thang nay", "share netflix", "tien netflix", "spotify premium", "mua spotify", "youtube pre", "ytb pre", "mua youtube", "mua vieon", "k+", "mua k+", "billiards", "tien bida 🎱", "bida hqua", "ck bida", "tra tien bida", "nap net", "tien may net", "choi net", "net xuyen dem", "the garena", "the zing", "nap game", "mua game", "mua game steam", "nạp fo4", "nap toc chien", "lien quan", "nap lq", "tien cf", "tiền cf", "cà phê", "ca phe", "uong cf", "cf ☕", "highland", "the coffee house", "tch", "katinat", "cf katinat", "phuc long", "tien cf t7", "cf hqua", "cf voi tui no", "cf cgai", "cf cty", "di pub", "tien pub", "bill pub", "di bar", "tien bar", "lounge", "bill lounge", "nhau 🍻", "tien nhậu", "bill nhau", "share tien nhau", "nhau oc", "nhau oc 1", "kara 🎤", "tien kara", "hat karaoke", "kara hqua", "bill kara", "di quay", "đi quẩy", "chill chill", "tien chill", "board game", "choi bg", "ma soi", "chơi ma sói", "thu cung", "cf meo", "cf chó", "xem kich", "vé kịch", "ve show", "vé ca nhạc", "ve concert", "mua ve show", "show ca nhac", "di nhac hoi", "nhạc hội", "ve edm", "vé festival", "ve khu vui choi", "khu vui chơi", "vinpearl", "sunworld", "ve vinwonders", "ve damsen", "đầm sen", "suoi tien", "suối tiên", "di thao cam vien", "tcv", "thảo cầm viên", "ve tcv", "bắn súng", "ban sung sơn", "paintball", "ban cung", "bắn cung", "chèo sup", "cheo sup", "tien cheo sup", "cam trai", "cắm trại", "thue do cam trai", "glamping", "tien glamping", "tour", "book tour", "tien tour", "di choi", "đi chơi", "tien di choi", "quỹ đi chơi", "quy an choi", "quỹ ăn chơi", "share tien di choi", "giai tri", "giải trí", "matxa", "massage", "tien matxa", "spa", "lam spa", "gội đầu", "goi dau", "goi dau duong sinh", "gdds", "lam nail", "nail", "tien nail", "lam toc", "làm tóc", "uon toc", "cat toc", "cắt tóc", "tien cat toc", "barber", "tien hớt tóc"
    ],
    "Sức khỏe": [
      "kham benh", "khám bệnh", "vien phi", "viện phí", "nha thuoc", "nhà thuốc", "mua thuoc", "mua thuốc", "long chau", "lhc", "pharmacity", "an khang", "cat kinh", "cắt kính", "nha khoa", "nhổ răng", "lam rang", "làm răng", "nieng rang", "niềng răng", "bhyte", "bhyt", "gym", "the gym", "thẻ gym", "cali", "california", "yoga", "pt", "tap gym", "the thao", "thể thao", "thuc pham bs", "tpcn", "whey", "vitamin", "kham da lieu", "khám da liễu", "kham mat", "khám mắt", "tien thuoc", "tiền thuốc", "tien vien", "tiền viện", "tien kham", "tiền khám", "kham sk", "khám sk", "kham tong quat", "khám tổng quát", "tam soat", "tầm soát", "xet nghiem", "xét nghiệm", "tien xet nghiem", "sieu am", "siêu âm", "chup xquang", "chụp xquang", "kham thai", "khám thai", "tien de", "tiền đẻ", "kham nhi", "khám nhi", "kham rang", "khám răng", "tram rang", "trám răng", "cay implant", "cạo vôi răng", "cao voi rang", "tay trang rang", "tẩy trắng răng", "mua kinh", "mua kính", "kinh can", "kính cận", "thay mat kinh", "thay tròng", "tien do mat", "đo mắt", "tien bhyt", "mua bhyt", "bao hiem y te", "bao hiem", "bảo hiểm sk", "mua thuoc cam", "thuốc cảm", "thuoc bo", "thuốc bổ", "thuoc t5", "tiền thuốc t5", "nhathuoc", "longchau", "mua thuoc lc", "tien gym", "the gym t5", "đóng tiền gym", "dong gym", "mua goi pt", "tien pt", "thue pt", "tien yoga", "tap yoga", "pilates", "tap pilates", "tien pilates", "bơi", "hoc boi", "vé bơi", "ve ho boi", "tien the thao", "thue san", "thuê sân", "san bong", "sân bóng", "tien san bong", "san cau long", "sân cầu lông", "tien san cau long", "san tennis", "sân tennis", "tien san pickleball", "pickleball", "tien vot", "mua vot", "mua banh", "mua giay the thao", "tien whey", "mua whey", "mass", "creatine", "omega 3", "mua omega3", "mua collagen", "collagen", "mua yến", "yến sào", "mua sam", "mua sâm", "đông trùng", "dong trung", "massage tri lieu", "matxa tri lieu", "cham cuu", "châm cứu", "vat ly tri lieu", "vật lý trị liệu", "kham dong y", "thuoc bac", "thuốc bắc", "thuoc nam", "boc thuoc", "bốc thuốc", "kham tam ly", "khám tâm lý", "tu van tam ly", "tư vấn tâm lý", "sk", "sức khoẻ", "tien kham benh", "kham bv", "benh vien", "bệnh viện", "ck bv", "thanh toan vien phi", "phi kham", "phí khám", "kham bhyt", "thuoc tay", "thuốc tây", "mua thuoc hqua", "kham hqua", "thuoc men", "thuốc men", "chua benh", "chữa bệnh", "phau thuat", "phẫu thuật", "tien phau thuat", "mổ", "tiền mổ", "tiêm ngừa", "tiem ngua", "tiem vacxin", "vaccine", "tien vacxin", "tiem vnvc", "vnvc", "mua vacxin", "chich ngua", "chích ngừa"
    ],
    "Giáo dục": [
      "hoc phi", "học phí", "hp", "tien hoc", "tiền học", "dong hoc", "đóng học", "tien hoc them", "tiền học thêm", "t.anh", "tieng anh", "tiếng anh", "ielts", "toeic", "tien sach", "tiền sách", "mua sach", "mua sách", "dong quy", "đóng quỹ", "quy lop", "quỹ lớp", "tien an ban tru", "tiền ăn bán trú", "hp dh", "hp đại học", "hoc phi ky 1", "học phí kỳ 1", "thue gia su", "thuê gia sư", "gia su", "gia sư", "khoa hoc", "khóa học", "hoc on", "học ôn", "tai lieu", "tài liệu", "in tai lieu", "in ấn", "photo", "tien photo", "tiền photo", "hoc phi t5", "hp t5", "tien hoc t5", "dong hoc phi", "đóng hp", "tien hoc tieng anh", "hoc tieng nhat", "tiếng nhật", "jlpt", "hoc tieng han", "tiếng hàn", "topik", "hoc tieng trung", "tiếng trung", "hsk", "le phi thi", "lệ phí thi", "phi thi ielts", "thi ielts", "tien thi toeic", "le phi thi dh", "dong tien hoc", "hoc phi con", "tien hoc be", "hp cho be", "mam non", "tien hoc mam non", "hoc phi mau giao", "tien an mau giao", "ban tru", "bán trú", "tien ban tru", "hp tieu hoc", "hp cap 2", "hp cap 3", "tien hoc ky 2", "hoc phi hoc ky", "tien tin chi", "tiền tín chỉ", "dong tin chi", "mua tin chi", "hoc lai", "tiền học lại", "thi lai", "tiền thi lại", "hoc cai thien", "tien hoc cai thien", "quy phu huynh", "quỹ phu huynh", "quy truong", "tien hoc kem", "học kèm", "hoc piano", "học piano", "tien hoc dan", "tiền học đàn", "hoc ve", "học vẽ", "tien hoc ve", "hoc boi", "tiền học bơi", "hoc vo", "học võ", "tien hoc vo", "hoc ky nang", "kỹ năng mềm", "khoa hoc online", "mua khoa hoc", "khoa hoc mkt", "hoc design", "hoc code", "học lập trình", "mua sach vo", "sách vở", "tien vo", "tiền vở", "dung cu hoc tap", "dụng cụ học tập", "mua but", "vpp", "van phong pham", "văn phòng phẩm", "tien dong phuc", "đồng phục", "mua dong phuc", "tien the hs", "thẻ sv", "lam the sv", "quy hoat dong", "ngoai khoa", "ngoại khóa", "tien ngoai khoa", "di thuc te", "đi thực tế", "kien tap", "kiến tập", "thuc tap", "thực tập", "bao cao", "báo cáo", "in luan van", "in đồ án", "khoa luan", "khóa luận", "tien in an", "sach tieng anh", "mua tu dien", "từ điển", "mua tai khoan", "tai khoan hoc", "tk elsa", "mua elsa", "duolingo", "ck hoc phi", "ck tien hoc", "nop hoc phi", "nộp hp", "nộp tiền học", "dong tien", "ck gia su", "luong gia su", "lương gia sư", "tra tien gia su", "trả tiền học", "hp 💸", "tien hoc 📚", "mua sach 📖", "photo tai lieu", "tien hoc av"
    ],
    "Hóa đơn & Tiện ích": [
      "tien dien", "tiền điện", "dien t5", "điện t5", "tien nuoc", "tiền nước", "nuoc", "nước", "internet", "cap quang", "wifi", "fpt", "viettel", "vnpt", "rac", "rác", "tien rac", "tiền rác", "phi quan ly", "phí quản lý", "pql", "phi cc", "phí chung cư", "chung cu", "chung cư", "dien thoai", "điện thoại", "nap the", "nạp thẻ", "tra sau", "trả sau", "thue bao", "thuê bao", "tra gop", "trả góp", "the tin dung", "thẻ tín dụng", "phi thuong nien", "phí thường niên", "dien nuoc", "điện nước", "tien dien nuoc", "tiền điện nước", "dien thang nay", "nuoc thang nay", "dong tien dien", "đóng tiền điện", "thanh toan dien", "tt dien", "thanh toan nuoc", "tt nuoc", "ck tien dien", "ck tien nuoc", "mang", "mạng", "tien mang", "tiền mạng", "dong tien mang", "internet fpt", "wifi viettel", "mang vnpt", "cuoc viettel", "cước viettel", "cuoc mobi", "cuoc vina", "tra sau viettel", "tra sau mobi", "nap the dt", "nạp đt", "nap card", "card dt", "tien dt", "tiền đt", "tien cap", "tiền cáp", "cap truyen hinh", "truyền hình cáp", "vtvcab", "sctv", "k+", "tien k+", "tien rac thang nay", "thu gom rac", "pql t5", "phi ql", "phi chung cu t5", "tien nha", "tiền nhà", "tien thue nha", "tiền thuê nhà", "thue nha", "thuê nhà", "thue tro", "thuê trọ", "tien tro", "tiền trọ", "dong tien tro", "tien phong", "tiền phòng", "tien coc nha", "cọc nhà", "tien gui xe cc", "gửi xe cc", "the thang", "tien tivi", "tra gop dt", "tra gop xe", "tra gop nha", "dong tra gop", "thanh toan tra gop", "fe credit", "home credit", "hcredit", "vay fe", "vay f88", "thanh toan the", "tt the tin dung", "the credit", "tt sao ke", "sao kê", "thanh toan credit", "du no", "dư nợ", "thanh toan du no", "phi dv", "phí dịch vụ", "tien ga", "tiền gas", "mua ga", "bình gas", "đổi gas", "doi gas", "nuoc bính", "nước bình", "doi nuoc", "đổi nước", "nuoc uong", "nuoc lavie", "bình lavie", "phi duy tri", "phí duy trì", "tien bao ve", "tiền bảo vệ", "bao ve", "an ninh", "tien an ninh", "dien sinh hoat", "nuoc sinh hoat", "tien dien 💡", "tien nuoc 💧", "wifi 📶", "mang t5", "dien thoai t5", "hoa don", "hóa đơn", "thanh toan hd", "tt hd", "tien tro t5", "tro thang 5", "tien nha thang nay", "ck tien phong", "ck tien tro", "nha tro", "thue mat bang", "tiền mặt bằng", "dien nuoc tro", "dien nuoc cc", "dong pql", "nộp phí ql", "tt internet", "tt wifi"
    ],
    "Chuyển tiền cá nhân": [
      "tra no", "trả nợ", "tra tien", "trả tiền", "vay", "cho vay", "vay tien", "vay tiền", "muon", "mượn", "muon tien", "mượn tiền", "tra tien an", "trả tiền ăn", "tra tien mua do", "tien sinh hoat", "tiền sinh hoạt", "ck", "chuyen tien", "chuyển tiền", "luong", "lương", "thuong", "thưởng", "luong t5", "lương t5", "ung luong", "ứng lương", "mung tuoi", "mừng tuổi", "li xi", "lì xì", "sn", "sinh nhat", "sinh nhật", "ck nha", "gui vo", "gửi vợ", "gui chong", "gửi chồng", "gui me", "gửi mẹ", "gui tien", "gửi tiền", "tra no nhe", "trả m nè", "tra tien hqua", "trả tiền nha", "ck tra", "ck tra no", "cho muon", "chuyển khoản", "ck nhe", "tien tieu vặt", "tiền tiêu vặt", "cho em", "cho con", "gui con", "gui ba", "gui ba me", "biếu ba mẹ", "bieu tien", "biếu", "tang", "tặng", "qua tang", "quà tặng", "mung sn", "mừng sn", "qua sn", "quà sn", "chuc mung sinh nhat", "cmsn", "happy birthday", "hbd", "tien an", "share tien", "tien hom qua", "tra gium", "trả giùm", "mua gium", "mua giùm", "ck gium", "tien dth", "tien ck", "tien ck luong", "chuyen luong", "phat luong", "luong thang nay", "luong parttime", "luong nv", "thuong le", "thưởng lễ", "thuong tet", "thưởng tết", "tien thuong", "bonus", "tien bonus", "hoa hong", "hoa hồng", "tien hh", "thanh toan", "tt", "ck tt", "gui", "gửi", "tra", "trả", "tien", "tiền", "tien t5", "ck t5", "ung tien", "ứng", "tien ung", "tra tien ung", "hoan tien", "hoàn tiền", "tra lai", "trả lại", "thoi tien", "thối tiền", "tra tien du", "trả dư", "ck test", "test", "thu ck", "thử ck", "mung cuoi", "mừng cưới", "tien mung", "di dam", "đi đám", "dam cuoi", "đám cưới", "tien dam cuoi", "phong bi", "phong bì", "dam ma", "đám ma", "chia buon", "chia buồn", "pha tam", "tang le", "tang lễ", "thoi noi", "thôi nôi", "day thang", "đầy tháng", "mung thoi noi", "mung tan gia", "tân gia", "dam gio", "đám giỗ", "tien dam gio", "dong gop gio", "tien quy", "tiền quỹ", "ck qũy", "dong tien", "ck a", "ck e", "ck chi", "gửi a", "gửi e", "gửi c", "ck ban", "tra ban", "tra m", "tra m ne", "tiền nhe", "ck nè", "nhan nhe", "nhận nhé", "tra tien ca phe", "tra tien nhau", "tra tien ve", "tien di choi hqua", "ck lai", "ck 💸", "luong 💰", "lixi 🧧", "li xi tet"
    ],
    "Khác": [
      "tien", "tiền", "ck", "chuyển khoản", "tt", "thanh toan", "thanh toán", "chuyển", "gửi", "gui", "nhan", "nhận", "ok", "done", "xong", "rồi", "roi", "ne", "nè", "nha", "đây", "day", "tien nha", "tiền nha", "ck ne", "ck nè", "gửi nhé", "gui nhe", "theo thoa thuan", "theo thỏa thuận", "nhu cu", "như cũ", "nhu da noi", "như đã nói", "viec hom qua", "việc hôm qua", "hom qua", "hôm qua", "hom bua", "hôm bữa", "t1", "t2", "t3", "t4", "t5", "t6", "t7", "t8", "t9", "t10", "t11", "t12", "thang nay", "tháng này", "tuan nay", "tuần này", "dot 1", "đợt 1", "dot 2", "phan con lai", "phần còn lại", "so du", "số dư", "khoan 1", "khoản 1", "khoan nay", "khoản này", "an + xang", "ăn + xăng", "cho va tien dien", "chợ và tiền điện", "tien phong vs mang", "tiền phòng + mạng + rác", "cf an trua", "cf + ăn trưa", "xang xe an uong", "xăng xe ăn uống", "mua do + cf", "mua đồ và cf", "xem phim an toi", "xem phim + ăn tối", "ve xe va khach san", "vé xe + khách sạn", "tien hoc + mua sach", "tiền học & mua sách", "kham benh + tien thuoc", "khám bệnh mua thuốc", "di cho + tien dien", "đi chợ vs đóng điện", "nuoc + rac + mang", "nước rác mạng", "tien an vs tien tro", "tiền ăn và tiền trọ", "ck mua ao + cf", "mua áo + trà sữa", "an nhau hat kara", "ăn nhậu kara", "bida cf", "bida & cf", "grab + an sang", "grab và ăn sáng", "tien xe + tien com", "tiền xe vs tiền cơm", "thue xe may + do xang", "thuê xe đổ xăng", "tien thuoc + xet nghiem", "nhổ răng lấy thuốc", "tap gym mua whey", "đóng gym + súp", "tien mang va dt", "tiền mạng điện thoại", "hoc phi va dong phuc", "hp + đồng phục", "mua dien thoai + op", "mua đt dán màn", "di sieu thi an kem", "đi sthị ăn kem", "tien nha dien nuoc", "nhà + điện + nước", "an trua va grab", "ăn trưa grab", "tien bida vs nuoc", "bida + nước", "mua hoa kem qua", "mua hoa + bánh", "tien cho va ship", "tiền chợ + ship", "ve xem phim bap nuoc", "vé phim + bắp nước", "kham mat cat kinh", "khám mắt + kính", "an toi vs di chill", "ăn tối đi pub", "cf va taxi", "aaaa", "bbbb", "abc", "xyz", "123", "12345", "test", "test ck", "thu ck", "thử ck", "hihi", "hehe", "haha", "kaka", "hic", "nhớ trả", "nho tra", "nho tra nhe", "mai tra", "mai trả", "okk", "okkk", "d", "dd", "fgh", "qwe", "asd", "zxc", "???", "!!!", "...", ",,,", "@@@", "###", "***", "check", "check ib", "check zalo", "ib nhe", "rep zalo", "rep tin nhan", "ngu di", "ngủ đi", "cam on", "cảm ơn", "tks", "thanks", "tkyou", "thank you", "chuc ngu ngon", "chúc ngủ ngon", "alo", "alooo", "nhan dc chua", "nhận đc chưa", "ting ting", "tingting", "💵", "💰", "👍", "❤️", "🥰", "ahihi", "bruh", "ảo", "vãi"
    ]
}

rows = []
for label, descriptions in raw_data.items():
    for desc in descriptions:
        rows.append({"description": desc.strip(), "label": label})

# Shuffle
import random
random.seed(42)
random.shuffle(rows)

with open("transactions.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["description", "label"])
    writer.writeheader()
    writer.writerows(rows)

print(f"Total: {len(rows)} samples")