from enum import Enum

class IntentTaxonomy(str, Enum):
    # General & Out of Scope
    FAQ_GENERAL = "FAQ_GENERAL"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"

    # Wallet Inquiries & Operations
    TRANSFER_GUIDE = "TRANSFER_GUIDE"
    FEE_INQUIRY = "FEE_INQUIRY"
    LIMIT_INQUIRY = "LIMIT_INQUIRY"
    TRANSACTION_STATUS = "TRANSACTION_STATUS"
    BALANCE_INQUIRY = "BALANCE_INQUIRY"
    PROMOTION_INQUIRY = "PROMOTION_INQUIRY"
    
    # Account & Linking
    ACCOUNT_SECURITY = "ACCOUNT_SECURITY"
    KYC_SUPPORT = "KYC_SUPPORT"
    BANK_LINKING = "BANK_LINKING"
    
    # Issues & Escalation
    FAILED_TRANSACTION = "FAILED_TRANSACTION"
    REFUND_OR_DISPUTE = "REFUND_OR_DISPUTE"
    FRAUD_OR_SCAM_REPORT = "FRAUD_OR_SCAM_REPORT"
    HUMAN_SUPPORT_REQUEST = "HUMAN_SUPPORT_REQUEST"
